### PR TITLE
Roles manager

### PR DESCRIPTION
**Pull request by kulmann**
We combined the roles middleware and cache into a roles manager. The manager doesn't expose the cache anymore and manages the state of the cache by fetching roles from the role service which don't exist in the cache, yet. This way we were able to get rid of the middleware entirely and make our service handlers ready for when we're starting to run permission checks on grpc calls.

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- roles/util.go  3
- roles/manager.go  6
         

Complexity decreasing per file
==============================
+ roles/cache.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-pkg/pullRequest?prid=6111725&bid=20003477)

**Review by PVince81 — APPROVED** [review]
:+1: code looks fine

**Comment by PVince81** [comment]
linter unhappy though

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- roles/util.go  3
- roles/manager.go  6
         

Complexity decreasing per file
==============================
+ roles/cache.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-pkg/pullRequest?prid=6111725&bid=20003477)

**Pull request merged**
