### PR TITLE
Upgrade micro/cli to v2

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by tboerger** [comment]
Drone fails

**Comment by DeepDiver1975** [comment]
> Drone fails

I know ... that's why it's a draft pr ... we need an upstream release of micro v2 first ... will come these days ....

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- log/stream.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-pkg/pullRequest?prid=4909476&bid=16253295)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- log/stream.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-pkg/pullRequest?prid=4909476&bid=16253295)

**Comment by C0rby** [comment]
I basically just copied the code for `Read` and `Stream` from go-micro. It's the simplest solution I guess but if it's bad for our use case e.g. because of the pessimistic locking in the buffer then I'll rewrite it.

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- log/stream.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-pkg/pullRequest?prid=4909476&bid=16253295)

**Review by refs — APPROVED** [review]
lgtm 👍 but a couple of remarks. Having a look at go-micro and that they added a structured in memory logger, we could use it and get rid of our wrapper; an experimental branch could be opened to explore this path, as we basically copied the memory log interface implementation to satisfy the contract.

If we get this merged you'd need to provide a changelog. Have a look at the changelog folder for steps to follow. Other than that, flawless /cc @C0rby

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- log/stream.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-pkg/pullRequest?prid=4909476&bid=16253295)

**Pull request merged**
