### PR TITLE
Grant access to protected branches to oc employees

### PR DESCRIPTION
**Pull request by refs**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Why are you proposing this? Even employees shall not push to master branch directly.
ci is there only for the purpose of syncing translations.

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
as commented - THX

**Review by tboerger — APPROVED** [review]

**Comment by tboerger** [comment]
Currently only ci group and org admins are allowed to merge PRs, that's why he has added that for me.

**Comment by DeepDiver1975** [comment]
ah -this is for the merger rights - got it - THX

**Pull request merged**
